version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: db_app
    ports:
      - 5432:5432
    env_file:
        - .env-non-dev
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: app
    command: bash -c 'alembic upgrade head && gunicorn src.main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000'
    ports:
      - 8000:8000
    depends_on:
      - db
      - celery
      - redis
    volumes:
      - .:/blog
    restart: always
  redis:
    image: redis
    env_file:
      - .env-non-dev
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
    restart: always
  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: bash -c 'celery -A  src.auth.task:celery worker --loglevel=INFO'
    depends_on:
      - redis
    restart: always
volumes:
  db_data: